services:
  was:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        # - linux/amd64
        - linux/arm64
    container_name: api-server
    # ports:
    #   - 8000:8000
    network_mode: "host"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./.env:/app/.env
      - ${DIR_STATIC}:/var/www/static
  
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${PG_USERNAME:-iksadnorth}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-q1w2e3r4}
      POSTGRES_DB: ${PG_DATABASE:-mytube}
    ports:
    - "5432:5432"
    volumes:
    - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
